# Configuration that does not always need to be changed

wandb:
    project: cs282-in-context-training
    entity: xi_cheng1017-university-of-california-berkeley
    notes:
    log_every_steps: 100
    name: 

training:
    num_tasks:
    num_training_examples:

